#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

if [ -e ${OPENSHIFT_REPO_DIR}/pom.xml ]
then
    cd ${OPENSHIFT_REPO_DIR}/
    mvn clean compile -U
else
    echo no webapp in ${OPENSHIFT_REPO_DIR}/active-webapp
    exit 1
fi


