#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
if [ -e ${OPENSHIFT_REPO_DIR}/active-webapp/pom.xml ]
then
    cd ${OPENSHIFT_REPO_DIR}/active-webapp
    nohup mvn --quiet -Djetty.host=$OPENSHIFT_INTERNAL_IP -Djetty.port=$OPENSHIFT_INTERNAL_PORT org.mortbay.jetty:jetty-maven-plugin:start >${OPENSHIFT_LOG_DIR}/jetty.log 2>&1 &
else
    echo no webapp in ${OPENSHIFT_REPO_DIR}/active-webapp
    exit 1
fi
